assert is_valid_password("aaaaaa1A"), "aaaaaa1A"
assert not is_valid_password("a"), "a"
assert not is_valid_password("aaaaaaaa"), "aaaaaaaa"
assert not is_valid_password("aaaaaaa1"), "aaaaaaa1"
assert not is_valid_password("aaaaaaaA"), "aaaaaaaA"
assert not is_valid_password("aaaaaaaA"), "aaaaaaaA"

assert not is_valid_password("1"), "1"
assert not is_valid_password("A"), "A"
assert not is_valid_password("A1"), "A1"
